id: I5C5752CA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:22:11+00:00'
last_modified: '2022-06-07T18:29:47.388695+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19474
  title: མདོ་སྡུད་པ་དང་རྡོ་རྗེ་གཅོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    274B:
      image_group_id: I1KG22499
      title: ''
      total_pages: 246
      order: 1
      base_file: 274B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
