id: P003224
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W19474
  title: མདོ་སྡུད་པ་དང་རྡོ་རྗེ་གཅོད་པ།
  author: ''
  volumes:
    8062a6dabca54415b04907005997bdd6:
      image_group_id: I1KG22499
      title: ''
      volume_number: 1
      total_pages: 246
      base_file: v001.txt
